---

- name: upload iso file to datastore
  vsphere_copy:
    host: "{{ lookup('env', 'VMWARE_HOST')|default(providers.vcenter.hostname) }}"
    login: "{{ lookup('env', 'VMWARE_USER')|default(providers.vcenter.username) }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD')|default(providers.vcenter.password) }}"
    src: "{{ playbook_dir }}/{{ temp_directory }}/linux_{{ linux_distro_name }}_ks_autogen.iso"
    datacenter: "{{ providers.vcenter.datacenter }}"
    datastore: "{{ providers.vcenter.datastore | default('datastore2') }}"
    path: "{{ iso_file }}"
    validate_certs: no